### ISSUE TITLE
Release latest changes to allow use in Scala 2.12

### ISSUE THREAD

**Issue by cory-p-oncota** [sbt/sbt-aspectj#31]
Could we get a release to bintray in the current state to allow downstream dependency upgrades that are currently blocked due to use of Scala 2.12?

**Comment by andrebeat** [comment]
This is needed for kamon integration.

**Comment by everylifetechnologies** [comment]
+1

**Comment by andrebeat** [comment]
Sorry to bump this again but it's impossible to use Kamon in Scala 2.12 without an updated version of this plugin. The issue has been fixed in #30 so it's just a matter of publishing a new version.

**Comment by sslavic** [comment]
@pvlugter can you please make a release with recent changes?

**Comment by pvlugter** [comment]
Sorry, I've been away on vacation and travelling.

Lightbend has not used this plugin for some time (since Typesafe Console). I'd like to hand this plugin off to the Kamon team, or others. And the plugin could use some love.

@sslavic has full rights to the repository already. Details for publishing sbt plugins to bintray can be found here: http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html.

**Comment by sslavic** [comment]
@cory-p-oncota would you like to take ownership of the project and release it yourself?

**Comment by pvlugter** [comment]
[0.11.0](https://github.com/sbt/sbt-aspectj/releases/tag/v0.11.0) is released. Note: includes some other changes too.
